#define LOCIC_TOKEN_INTERFACE                       1
#define LOCIC_TOKEN_CLASS                           2
#define LOCIC_TOKEN_LCURLYBRACKET                   3
#define LOCIC_TOKEN_RCURLYBRACKET                   4
#define LOCIC_TOKEN_LROUNDBRACKET                   5
#define LOCIC_TOKEN_RROUNDBRACKET                   6
#define LOCIC_TOKEN_UCNAME                          7
#define LOCIC_TOKEN_LCNAME                          8
#define LOCIC_TOKEN_VOIDNAME                        9
#define LOCIC_TOKEN_BOOLNAME                       10
#define LOCIC_TOKEN_INTNAME                        11
#define LOCIC_TOKEN_FLOATNAME                      12
#define LOCIC_TOKEN_CONST                          13
#define LOCIC_TOKEN_STAR                           14
#define LOCIC_TOKEN_SEMICOLON                      15
#define LOCIC_TOKEN_COMMA                          16
#define LOCIC_TOKEN_IF                             17
#define LOCIC_TOKEN_ELSE                           18
#define LOCIC_TOKEN_FOR                            19
#define LOCIC_TOKEN_COLON                          20
#define LOCIC_TOKEN_WHILE                          21
#define LOCIC_TOKEN_AUTO                           22
#define LOCIC_TOKEN_SETEQUAL                       23
#define LOCIC_TOKEN_AT                             24
#define LOCIC_TOKEN_RETURN                         25
#define LOCIC_TOKEN_BOOLCONSTANT                   26
#define LOCIC_TOKEN_INTCONSTANT                    27
#define LOCIC_TOKEN_FLOATCONSTANT                  28
#define LOCIC_TOKEN_DOT                            29
#define LOCIC_TOKEN_PTRACCESS                      30
#define LOCIC_TOKEN_PLUS                           31
#define LOCIC_TOKEN_MINUS                          32
#define LOCIC_TOKEN_EXCLAIMMARK                    33
#define LOCIC_TOKEN_AMPERSAND                      34
#define LOCIC_TOKEN_FORWARDSLASH                   35
#define LOCIC_TOKEN_ISEQUAL                        36
#define LOCIC_TOKEN_NOTEQUAL                       37
#define LOCIC_TOKEN_GREATEROREQUAL                 38
#define LOCIC_TOKEN_LESSOREQUAL                    39
#define LOCIC_TOKEN_QUESTIONMARK                   40
