#define LOCIC_TOKEN_CLASS                           1
#define LOCIC_TOKEN_LCURLYBRACKET                   2
#define LOCIC_TOKEN_RCURLYBRACKET                   3
#define LOCIC_TOKEN_LROUNDBRACKET                   4
#define LOCIC_TOKEN_RROUNDBRACKET                   5
#define LOCIC_TOKEN_UCNAME                          6
#define LOCIC_TOKEN_LCNAME                          7
#define LOCIC_TOKEN_VOIDNAME                        8
#define LOCIC_TOKEN_BOOLNAME                        9
#define LOCIC_TOKEN_INTNAME                        10
#define LOCIC_TOKEN_FLOATNAME                      11
#define LOCIC_TOKEN_CONST                          12
#define LOCIC_TOKEN_STAR                           13
#define LOCIC_TOKEN_SEMICOLON                      14
#define LOCIC_TOKEN_COMMA                          15
#define LOCIC_TOKEN_IF                             16
#define LOCIC_TOKEN_ELSE                           17
#define LOCIC_TOKEN_FOR                            18
#define LOCIC_TOKEN_COLON                          19
#define LOCIC_TOKEN_WHILE                          20
#define LOCIC_TOKEN_AUTO                           21
#define LOCIC_TOKEN_SETEQUAL                       22
#define LOCIC_TOKEN_AT                             23
#define LOCIC_TOKEN_RETURN                         24
#define LOCIC_TOKEN_BOOLCONSTANT                   25
#define LOCIC_TOKEN_INTCONSTANT                    26
#define LOCIC_TOKEN_FLOATCONSTANT                  27
#define LOCIC_TOKEN_DOT                            28
#define LOCIC_TOKEN_PTRACCESS                      29
#define LOCIC_TOKEN_PLUS                           30
#define LOCIC_TOKEN_MINUS                          31
#define LOCIC_TOKEN_EXCLAIMMARK                    32
#define LOCIC_TOKEN_AMPERSAND                      33
#define LOCIC_TOKEN_FORWARDSLASH                   34
#define LOCIC_TOKEN_ISEQUAL                        35
#define LOCIC_TOKEN_QUESTIONMARK                   36
