#define LOCIC_TOKEN_ERROR                           1
#define LOCIC_TOKEN_INTERFACE                       2
#define LOCIC_TOKEN_CLASS                           3
#define LOCIC_TOKEN_LCURLYBRACKET                   4
#define LOCIC_TOKEN_RCURLYBRACKET                   5
#define LOCIC_TOKEN_LROUNDBRACKET                   6
#define LOCIC_TOKEN_RROUNDBRACKET                   7
#define LOCIC_TOKEN_UCNAME                          8
#define LOCIC_TOKEN_LCNAME                          9
#define LOCIC_TOKEN_VOIDNAME                       10
#define LOCIC_TOKEN_BOOLNAME                       11
#define LOCIC_TOKEN_INTNAME                        12
#define LOCIC_TOKEN_FLOATNAME                      13
#define LOCIC_TOKEN_CONST                          14
#define LOCIC_TOKEN_STAR                           15
#define LOCIC_TOKEN_SEMICOLON                      16
#define LOCIC_TOKEN_COMMA                          17
#define LOCIC_TOKEN_IF                             18
#define LOCIC_TOKEN_ELSE                           19
#define LOCIC_TOKEN_FOR                            20
#define LOCIC_TOKEN_COLON                          21
#define LOCIC_TOKEN_WHILE                          22
#define LOCIC_TOKEN_AUTO                           23
#define LOCIC_TOKEN_SETEQUAL                       24
#define LOCIC_TOKEN_AT                             25
#define LOCIC_TOKEN_RETURN                         26
#define LOCIC_TOKEN_BOOLCONSTANT                   27
#define LOCIC_TOKEN_INTCONSTANT                    28
#define LOCIC_TOKEN_FLOATCONSTANT                  29
#define LOCIC_TOKEN_DOT                            30
#define LOCIC_TOKEN_PTRACCESS                      31
#define LOCIC_TOKEN_PLUS                           32
#define LOCIC_TOKEN_MINUS                          33
#define LOCIC_TOKEN_EXCLAIMMARK                    34
#define LOCIC_TOKEN_AMPERSAND                      35
#define LOCIC_TOKEN_FORWARDSLASH                   36
#define LOCIC_TOKEN_ISEQUAL                        37
#define LOCIC_TOKEN_NOTEQUAL                       38
#define LOCIC_TOKEN_GREATEROREQUAL                 39
#define LOCIC_TOKEN_LESSOREQUAL                    40
#define LOCIC_TOKEN_QUESTIONMARK                   41
